"use client";

import { useEffect, useState } from "react";
import { Trash2 } from "lucide-react";
import { toast } from "sonner";
import { api } from "@/lib/api";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { Dialog } from "@/components/ui/dialog";

type Doc = {id:string; filename:string; n_chunks:number; uploaded_at:string; status:string};
export default function DocsPage(){const [docs,setDocs]=useState<Doc[]>([]);const [loading,setLoading]=useState(true);const [selected,setSelected]=useState<Doc|null>(null);const load=()=>api<Doc[]>("/documents").then(setDocs).catch(e=>toast.error(e.message)).finally(()=>setLoading(false));useEffect(()=>{load()},[]);async function remove(){if(!selected)return;try{await api(`/documents/${selected.id}`,{method:"DELETE"});setSelected(null);load();toast.success("Document removed")}catch(e){toast.error((e as Error).message)}}return <section className="py-8"><div className="mb-10"><div className="text-xs uppercase tracking-[.16em] text-foreground/40">Corpus</div><h1 className="mt-2 text-3xl font-semibold tracking-tight">Documents</h1><p className="mt-2 text-sm text-foreground/55">The indexed material available to your research workspace.</p></div>{loading?<div className="space-y-2"><Skeleton className="h-16"/><Skeleton className="h-16"/><Skeleton className="h-16"/></div>:docs.length===0?<Card className="p-10 text-center"><div className="text-sm font-medium">No documents yet</div><div className="mt-1 text-xs text-foreground/45">Upload your first PDF to build the corpus.</div></Card>:<div className="overflow-hidden rounded-xl border border-border"><div className="grid grid-cols-[1fr_100px_150px_80px] border-b border-border px-5 py-3 text-[11px] uppercase tracking-wider text-foreground/40"><span>Document</span><span>Chunks</span><span>Uploaded</span><span/></div>{docs.map(d=><div key={d.id} className="grid grid-cols-[1fr_100px_150px_80px] items-center px-5 py-4 text-sm"><div><div className="font-medium">{d.filename}</div><div className="mt-1 text-[11px] text-foreground/40">{d.id}</div></div><div>{d.n_chunks}</div><div className="text-foreground/55">{new Date(d.uploaded_at).toLocaleString()}</div><div><button className="rounded-md p-2 text-foreground/40 hover:bg-foreground/[.05] hover:text-foreground" onClick={()=>setSelected(d)}><Trash2 size={15}/></button></div></div>)}</div>}<Dialog open={Boolean(selected)} onClose={()=>setSelected(null)} title="Remove document"><p className="text-sm leading-6 text-foreground/60">This removes the document metadata and its indexed vectors. The action cannot be undone.</p><div className="mt-6 flex justify-end gap-2"><button className="h-9 rounded-md border border-border px-3 text-sm" onClick={()=>setSelected(null)}>Cancel</button><button className="h-9 rounded-md bg-foreground px-3 text-sm text-background" onClick={remove}>Remove</button></div></Dialog></section>}
